<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="chetanpc" name="PDP_pages1_test.InocationCountAndTimeout" tests="6" failures="0" timestamp="06 Aug 2022 08:45:01 GMT" time="73.524" errors="1">
  <testcase name="count" time="16.103" classname="PDP_pages1_test.InocationCountAndTimeout"/>
  <testcase name="count" time="12.608" classname="PDP_pages1_test.InocationCountAndTimeout"/>
  <testcase name="count" time="10.005" classname="PDP_pages1_test.InocationCountAndTimeout"/>
  <testcase name="count" time="10.478" classname="PDP_pages1_test.InocationCountAndTimeout"/>
  <testcase name="Timeout" time="14.575" classname="PDP_pages1_test.InocationCountAndTimeout"/>
  <testcase name="expectedexception" time="9.755" classname="PDP_pages1_test.InocationCountAndTimeout">
    <error type="org.testng.TestException" message="
Method InocationCountAndTimeout.expectedexception()[pri:0, instance:PDP_pages1_test.InocationCountAndTimeout@6eebc39e] should have thrown an exception of type class java.text.NumberFormat">
      <![CDATA[org.testng.TestException: 
Method InocationCountAndTimeout.expectedexception()[pri:0, instance:PDP_pages1_test.InocationCountAndTimeout@6eebc39e] should have thrown an exception of type class java.text.NumberFormat
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1140)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- expectedexception -->
</testsuite> <!-- PDP_pages1_test.InocationCountAndTimeout -->
